import Foundation
import SwiftProjectLintModels
import LintStudioCore

/// Formats lint issues as an HTML report using the shared LintStudioCore template.
public struct HTMLFormatter: IssueFormatterProtocol {
    public init() {}

    public func format(issues: [LintIssue]) -> String {
        let errorCount = issues.filter { $0.severity == .error }.count
        let warningCount = issues.filter { $0.severity == .warning }.count
        let infoCount = issues.filter { $0.severity == .info }.count
        let fileCount = Set(issues.map(\.filePath)).count
        let ruleCount = Set(issues.map { $0.ruleName.rawValue }).count
        let timestamp = DateFormatter.localizedString(
            from: Date.now,
            dateStyle: .long,
            timeStyle: .short
        )

        var body = ""

        body += summarySection(
            total: issues.count,
            errors: errorCount,
            warnings: warningCount,
            infos: infoCount,
            files: fileCount,
            rules: ruleCount
        )

        body += detailedListSection(issues: issues)

        return HTMLReportTemplate.wrapInHTML(
            title: "SwiftProjectLint Report",
            timestamp: timestamp,
            body: body,
            footerText: "Generated by SwiftProjectLint"
        )
    }

    // MARK: - Sections

    private func summarySection(
        total: Int,
        errors: Int,
        warnings: Int,
        infos: Int,
        files: Int,
        rules: Int
    ) -> String {
        """
        <section class="summary">
          <h2>Summary</h2>
          <div class="cards">
            <div class="card">
              <div class="card-value">\(total)</div>
              <div class="card-label">Total Issues</div>
            </div>
            <div class="card card-error">
              <div class="card-value">\(errors)</div>
              <div class="card-label">Errors</div>
            </div>
            <div class="card card-warning">
              <div class="card-value">\(warnings)</div>
              <div class="card-label">Warnings</div>
            </div>
            <div class="card">
              <div class="card-value">\(infos)</div>
              <div class="card-label">Info</div>
            </div>
            <div class="card">
              <div class="card-value">\(files)</div>
              <div class="card-label">Files Affected</div>
            </div>
            <div class="card">
              <div class="card-value">\(rules)</div>
              <div class="card-label">Rules Triggered</div>
            </div>
          </div>
        </section>
        """
    }

    private func detailedListSection(issues: [LintIssue]) -> String {
        let grouped = Dictionary(grouping: issues, by: \.filePath)
        let sortedFiles = grouped.keys.sorted()

        var html = "<section class=\"details\"><h2>Issues by File</h2>\n"

        for file in sortedFiles {
            let fileIssues = grouped[file] ?? []
            let fileName = URL(fileURLWithPath: file).lastPathComponent
            html += """
              <div class="file-group">
                <h3>\(HTMLEscaping.escape(fileName))
                  <span class="file-count">\(fileIssues.count) issues</span>
                </h3>
                <p class="file-path">\(HTMLEscaping.escape(file))</p>
                <table>
                  <thead>
                    <tr>
                      <th>Line</th><th>Severity</th><th>Rule</th><th>Message</th>
                    </tr>
                  </thead>
                  <tbody>
            """

            for issue in fileIssues.sorted(by: { $0.lineNumber < $1.lineNumber }) {
                let severityClass = severityCSSClass(issue.severity)
                let severityLabel = issue.severity.rawValue.capitalized
                html += """
                    <tr>
                      <td class="line-num">\(issue.lineNumber)</td>
                      <td class="\(severityClass)">\(severityLabel)</td>
                      <td class="rule-id">\(HTMLEscaping.escape(issue.ruleName.rawValue))</td>
                      <td>\(HTMLEscaping.escape(issue.message))</td>
                    </tr>
                """

                if let suggestion = issue.suggestion {
                    html += """
                        <tr class="snippet-row">
                          <td colspan="4"><pre class="snippet">\(HTMLEscaping.escape(suggestion))</pre></td>
                        </tr>
                    """
                }
            }

            html += "  </tbody></table></div>\n"
        }

        html += "</section>\n"
        return html
    }

    private func severityCSSClass(_ severity: IssueSeverity) -> String {
        switch severity {
        case .error: "severity-error"
        case .warning: "severity-warning"
        case .info: "severity-warning"
        }
    }
}
