import Core
import Foundation
import Testing

struct HTMLFormatterTests {
    @Test
    func producesValidHTMLDocument() {
        let issue = LintIssue(
            severity: .warning,
            message: "Test issue",
            filePath: "View.swift",
            lineNumber: 5,
            suggestion: "Fix it",
            ruleName: .fatView
        )
        let html = HTMLFormatter().format(issues: [issue])

        #expect(html.contains("<!DOCTYPE html>"))
        #expect(html.contains("<title>SwiftProjectLint Report</title>"))
        #expect(html.contains("Generated by SwiftProjectLint"))
    }

    @Test
    func includesSummarySection() {
        let issues = [
            LintIssue(
                severity: .error, message: "Error", filePath: "A.swift",
                lineNumber: 1, suggestion: nil, ruleName: .fatView
            ),
            LintIssue(
                severity: .warning, message: "Warning", filePath: "B.swift",
                lineNumber: 2, suggestion: nil, ruleName: .catchWithoutHandling
            ),
            LintIssue(
                severity: .info, message: "Info", filePath: "C.swift",
                lineNumber: 3, suggestion: nil, ruleName: .dateNow
            )
        ]
        let html = HTMLFormatter().format(issues: issues)

        #expect(html.contains("Total Issues"))
        #expect(html.contains("Errors"))
        #expect(html.contains("Warnings"))
        #expect(html.contains("Info"))
    }

    @Test
    func includesDetailedListSection() {
        let issue = LintIssue(
            severity: .error,
            message: "Force try detected",
            filePath: "/project/Sources/App.swift",
            lineNumber: 42,
            suggestion: "Use do-catch instead",
            ruleName: .forceTry
        )
        let html = HTMLFormatter().format(issues: [issue])

        #expect(html.contains("Issues by File"))
        #expect(html.contains("App.swift"))
        #expect(html.contains("Force try detected"))
        #expect(html.contains("Use do-catch instead"))
    }

    @Test
    func escapesHTMLInMessages() {
        let issue = LintIssue(
            severity: .warning,
            message: "Use <View> instead of <Text>",
            filePath: "Test.swift",
            lineNumber: 1,
            suggestion: nil,
            ruleName: .fatView
        )
        let html = HTMLFormatter().format(issues: [issue])

        #expect(html.contains("&lt;View&gt;"))
        #expect(html.contains("<View>") == false)
    }

    @Test
    func handlesEmptyIssues() {
        let html = HTMLFormatter().format(issues: [])

        #expect(html.contains("<!DOCTYPE html>"))
        #expect(html.contains("Total Issues"))
    }

    /// The header timestamp comes from the injected clock, not the wall clock. Byte-comparing
    /// laws (`ReportOrderDeterminismLawsTests`) pin it this way; if the seam stopped reaching the
    /// header they would go back to failing only when a run straddles a minute boundary.
    @Test
    func rendersTheInjectedGenerationTime() {
        let instant = Date(timeIntervalSince1970: 1_800_000_000)
        let formatter = HTMLFormatter { instant }
        let html = formatter.format(issues: [])
        let expected = DateFormatter.localizedString(from: instant, dateStyle: .long, timeStyle: .short)

        #expect(html.contains("Generated \(expected)"))
    }

    /// HTML is the one formatter that reorders what it is given — files sorted, then rows within a
    /// file — so the order it imposes has to be total. Ordering rows by line alone left two
    /// findings on the same line in arrival order, which only an unguaranteed stable sort kept.
    @Test
    func sameLineFindingsRenderInOneOrderWhateverOrderTheyArriveIn() {
        let sameLine = [
            LintIssue(
                severity: .warning, message: "Force unwrap", filePath: "A.swift",
                lineNumber: 7, suggestion: nil, ruleName: .forceUnwrap
            ),
            LintIssue(
                severity: .error, message: "Force try", filePath: "A.swift",
                lineNumber: 7, suggestion: nil, ruleName: .forceTry
            )
        ]
        let formatter = HTMLFormatter { Date(timeIntervalSince1970: 1_800_000_000) }

        #expect(formatter.format(issues: sameLine) == formatter.format(issues: sameLine.reversed()))
    }

    @Test
    func includesEmbeddedCSS() {
        let html = HTMLFormatter().format(issues: [])

        #expect(html.contains("<style>"))
        #expect(html.contains("prefers-color-scheme: dark"))
    }
}
