import Foundation
import Testing
import Core
@testable import CLI

struct HTMLFormatterTests {
    @Test
    func producesValidHTMLDocument() {
        let issue = LintIssue(
            severity: .warning,
            message: "Test issue",
            filePath: "View.swift",
            lineNumber: 5,
            suggestion: "Fix it",
            ruleName: .fatView
        )
        let html = HTMLFormatter().format(issues: [issue])

        #expect(html.contains("<!DOCTYPE html>"))
        #expect(html.contains("<title>SwiftProjectLint Report</title>"))
        #expect(html.contains("Generated by SwiftProjectLint"))
    }

    @Test
    func includesSummarySection() {
        let issues = [
            LintIssue(
                severity: .error, message: "Error", filePath: "A.swift",
                lineNumber: 1, suggestion: nil, ruleName: .fatView
            ),
            LintIssue(
                severity: .warning, message: "Warning", filePath: "B.swift",
                lineNumber: 2, suggestion: nil, ruleName: .catchWithoutHandling
            ),
            LintIssue(
                severity: .info, message: "Info", filePath: "C.swift",
                lineNumber: 3, suggestion: nil, ruleName: .dateNow
            )
        ]
        let html = HTMLFormatter().format(issues: issues)

        #expect(html.contains("Total Issues"))
        #expect(html.contains("Errors"))
        #expect(html.contains("Warnings"))
        #expect(html.contains("Info"))
    }

    @Test
    func includesDetailedListSection() {
        let issue = LintIssue(
            severity: .error,
            message: "Force try detected",
            filePath: "/project/Sources/App.swift",
            lineNumber: 42,
            suggestion: "Use do-catch instead",
            ruleName: .forceTry
        )
        let html = HTMLFormatter().format(issues: [issue])

        #expect(html.contains("Issues by File"))
        #expect(html.contains("App.swift"))
        #expect(html.contains("Force try detected"))
        #expect(html.contains("Use do-catch instead"))
    }

    @Test
    func escapesHTMLInMessages() {
        let issue = LintIssue(
            severity: .warning,
            message: "Use <View> instead of <Text>",
            filePath: "Test.swift",
            lineNumber: 1,
            suggestion: nil,
            ruleName: .fatView
        )
        let html = HTMLFormatter().format(issues: [issue])

        #expect(html.contains("&lt;View&gt;"))
        #expect(!html.contains("<View>"))
    }

    @Test
    func handlesEmptyIssues() {
        let html = HTMLFormatter().format(issues: [])

        #expect(html.contains("<!DOCTYPE html>"))
        #expect(html.contains("Total Issues"))
    }

    @Test
    func includesEmbeddedCSS() {
        let html = HTMLFormatter().format(issues: [])

        #expect(html.contains("<style>"))
        #expect(html.contains("prefers-color-scheme: dark"))
    }
}
