//
//  RuleDocumentationLoader.swift
//  SwiftProjectLint
//
//  Created by Joseph Cursio on 3/18/26.
//

import Foundation
import Core

/// Loads rule documentation markdown from the app bundle.
struct RuleDocumentationLoader {
    static func loadDocumentation(for rule: RuleIdentifier) -> String? {
        let filename = documentationFileName(for: rule)
        guard let url = Bundle.module.url(
            forResource: filename,
            withExtension: "md"
        ) else { return nil }
        return try? String(contentsOf: url, encoding: .utf8)
    }

    // MARK: - Private

    /// Converts a RuleIdentifier case name to its kebab-case documentation filename.
    ///
    /// Uses the camelCase case name (e.g. `forEachWithoutID`) rather than the raw value
    /// so the result matches the filenames generated by the documentation tooling.
    static func documentationFileName(for rule: RuleIdentifier) -> String {
        // Special cases — the algorithmic kebab-conversion can't recover these
        // because the doc filenames intentionally keep multi-word Apple brand
        // names glued together (`SwiftData` → `swiftdata`, `CloudKit` →
        // `cloudkit`) and can't disambiguate two consecutive acronyms (`IDUI`).
        switch rule {
        case .forEachWithoutIDUI: return "for-each-without-id-ui"
        case .swiftDataUniqueAttributeCloudKit: return "swiftdata-unique-attribute-cloudkit"
        default: break
        }
        return camelCaseToKebab(String(describing: rule))
    }

    /// Converts a camelCase string to kebab-case.
    ///
    /// Handles acronyms correctly: `forEachWithoutID` → `for-each-without-id`,
    /// `unsafeURL` → `unsafe-url`. Digit→letter boundaries get a dash too so
    /// `ios17ObservationMigration` becomes `ios17-observation-migration`
    /// (the doc filename keeps `ios17` glued because the rawValue token
    /// `iOS 17` collapses on doc-author convention).
    private static func camelCaseToKebab(_ input: String) -> String {
        var result = ""
        let chars = Array(input)
        for idx in 0..<chars.count {
            let char = chars[idx]
            guard char.isUppercase else { result += String(char); continue }
            let prevIsLower = idx > 0 && chars[idx - 1].isLowercase
            let prevIsUpper = idx > 0 && chars[idx - 1].isUppercase
            let prevIsDigit = idx > 0 && chars[idx - 1].isNumber
            let nextIsLower = idx < chars.count - 1 && chars[idx + 1].isLowercase
            if prevIsLower || prevIsDigit || (prevIsUpper && nextIsLower) {
                result += "-"
            }
            result += char.lowercased()
        }
        return result
    }
}
