//
//  RuleDocumentationLoader.swift
//  SwiftProjectLint
//
//  Created by Joseph Cursio on 3/18/26.
//

import Foundation
import SwiftProjectLintCore

/// Loads rule documentation markdown from the app bundle.
struct RuleDocumentationLoader {
    static func loadDocumentation(for rule: RuleIdentifier) -> String? {
        let filename = documentationFileName(for: rule)
        guard let url = Bundle.module.url(
            forResource: filename,
            withExtension: "md",
            subdirectory: "rules"
        ) else { return nil }
        return try? String(contentsOf: url, encoding: .utf8)
    }

    // MARK: - Private

    /// Converts a RuleIdentifier case name to its kebab-case documentation filename.
    ///
    /// Uses the camelCase case name (e.g. `forEachWithoutID`) rather than the raw value
    /// so the result matches the filenames generated by the documentation tooling.
    static func documentationFileName(for rule: RuleIdentifier) -> String {
        // Special case: two consecutive acronyms (IDUI) can't be split algorithmically
        if rule == .forEachWithoutIDUI { return "for-each-without-id-ui" }
        return camelCaseToKebab(String(describing: rule))
    }

    /// Converts a camelCase string to kebab-case.
    ///
    /// Handles acronyms correctly: `forEachWithoutID` → `for-each-without-id`,
    /// `unsafeURL` → `unsafe-url`.
    private static func camelCaseToKebab(_ input: String) -> String {
        var result = ""
        let chars = Array(input)
        for idx in 0..<chars.count {
            let char = chars[idx]
            guard char.isUppercase else { result += String(char); continue }
            let prevIsLower = idx > 0 && chars[idx - 1].isLowercase
            let prevIsUpper = idx > 0 && chars[idx - 1].isUppercase
            let nextIsLower = idx < chars.count - 1 && chars[idx + 1].isLowercase
            if prevIsLower || (prevIsUpper && nextIsLower) {
                result += "-"
            }
            result += char.lowercased()
        }
        return result
    }
}
